#ifndef	DIO_CONFIG_H
#define	DIO_CONFIG_H

#define	HIGH		1
#define	LOW		0
#define	HIGH_IMPEDANCE		0
#define	PULL_UP		1
#define	OUTPUT		1
#define	INPUT		0


#define	PORTA__DIR		OUTPUT
#define	PORTA__VAL		High

#define	PORTA_PIN1_DIR		INPUT
#define	PORTA_PIN1_VAL		HIGH_IMPEDANCE

#define	PORTA_PIN2_DIR		INPUT
#define	PORTA_PIN2_VAL		HIGH_IMPEDANCE

#define	PORTA_PIN3_DIR		INPUT
#define	PORTA_PIN3_VAL		HIGH_IMPEDANCE

#define	PORTA_PIN4_DIR		INPUT
#define	PORTA_PIN4_VAL		HIGH_IMPEDANCE

#define	PORTA_PIN5_DIR		INPUT
#define	PORTA_PIN5_VAL		HIGH_IMPEDANCE

#define	PORTA_PIN6_DIR		INPUT
#define	PORTA_PIN6_VAL		HIGH_IMPEDANCE

#define	PORTA_PIN7_DIR		INPUT
#define	PORTA_PIN7_VAL		HIGH_IMPEDANCE

#define	PORTB_PIN0_DIR		INPUT
#define	PORTB_PIN0_VAL		HIGH_IMPEDANCE

#define	PORTB_PIN1_DIR		INPUT
#define	PORTB_PIN1_VAL		HIGH_IMPEDANCE

#define	PORTB_PIN2_DIR		INPUT
#define	PORTB_PIN2_VAL		HIGH_IMPEDANCE

#define	PORTB_PIN3_DIR		INPUT
#define	PORTB_PIN3_VAL		HIGH_IMPEDANCE

#define	PORTB_PIN4_DIR		INPUT
#define	PORTB_PIN4_VAL		HIGH_IMPEDANCE

#define	PORTB_PIN5_DIR		INPUT
#define	PORTB_PIN5_VAL		HIGH_IMPEDANCE

#define	PORTB_PIN6_DIR		INPUT
#define	PORTB_PIN6_VAL		HIGH_IMPEDANCE

#define	PORTB_PIN7_DIR		INPUT
#define	PORTB_PIN7_VAL		HIGH_IMPEDANCE

#define	PORTC_PIN0_DIR		INPUT
#define	PORTC_PIN0_VAL		HIGH_IMPEDANCE

#define	PORTC_PIN1_DIR		INPUT
#define	PORTC_PIN1_VAL		HIGH_IMPEDANCE

#define	PORTC_PIN2_DIR		INPUT
#define	PORTC_PIN2_VAL		HIGH_IMPEDANCE

#define	PORTC_PIN3_DIR		INPUT
#define	PORTC_PIN3_VAL		HIGH_IMPEDANCE

#define	PORTC_PIN4_DIR		INPUT
#define	PORTC_PIN4_VAL		HIGH_IMPEDANCE

#define	PORTC_PIN5_DIR		INPUT
#define	PORTC_PIN5_VAL		HIGH_IMPEDANCE

#define	PORTC_PIN6_DIR		INPUT
#define	PORTC_PIN6_VAL		HIGH_IMPEDANCE

#define	PORTC_PIN7_DIR		INPUT
#define	PORTC_PIN7_VAL		HIGH_IMPEDANCE

#define	PORTD_PIN0_DIR		INPUT
#define	PORTD_PIN0_VAL		HIGH_IMPEDANCE

#define	PORTD_PIN1_DIR		INPUT
#define	PORTD_PIN1_VAL		HIGH_IMPEDANCE

#define	PORTD_PIN2_DIR		INPUT
#define	PORTD_PIN2_VAL		HIGH_IMPEDANCE

#define	PORTD_PIN3_DIR		INPUT
#define	PORTD_PIN3_VAL		HIGH_IMPEDANCE

#define	PORTD_PIN4_DIR		INPUT
#define	PORTD_PIN4_VAL		HIGH_IMPEDANCE

#define	PORTD_PIN5_DIR		INPUT
#define	PORTD_PIN5_VAL		HIGH_IMPEDANCE

#define	PORTD_PIN6_DIR		INPUT
#define	PORTD_PIN6_VAL		HIGH_IMPEDANCE

#define	PORTD_PIN7_DIR		INPUT
#define	PORTD_PIN7_VAL		HIGH_IMPEDANCE


#endif